#spring:
#    database:
#        driverClassName: org.postgresql.Driver
#    datasource:
#        url: ${JDBC_DATABASE_URL}
#        maxActive: 10
#        maxIdle: 5
#        minIdle: 2
#        initialSize: 5
#        removeAbandoned: true
#    jpa:
#        database: POSTGRESQL
#        show-sql: true
#        hibernate:
#            ddl-auto: create-drop